Fix directory not being deleted & add TEMP_DIR field for usage in child projects
idrsolutions/base-microservice-example pull request #25
Opened 2020-11-12 16:06 UTC by leonatherton

2020-11-13 12:25 UTC, Amy1612 approved these changes

2020-11-13 14:36 UTC, KieranFrance approved these changes

2020-11-16 16:06 UTC, daniel-warren approved these changes

2020-11-16 16:09 UTC, daniel-warren requested changes
@leonatherton - Should this change include a version number increase? I believe it should be a patch change?

2020-11-16 17:51 UTC, leonatherton commented
@daniel-warren my understanding is that Kieran will update version numbers when merging develop into master at the end of the cycle.

2020-11-17 15:09 UTC, KieranFrance commented
@daniel-warren That is correct.

2020-11-18 09:18 UTC, daniel-warren approved these changes

2020-11-23 12:22 UTC, merged