Abstracted file storing and implemented remote storage
idrsolutions/base-microservice-example pull request #46
Opened 2021-12-02 15:17 UTC by JacobIDR

- Currently defaults to the LocalStorage implementation which behaves the same as before.
- Important variables like bucket names and azure's containerName are not accessable as we need to decide if their values should be set using config files or with the constructor
- This will require some changes to the child microservices as it takes from them the responsibility of zipping up the files and uploading them
  - This means the zip can remain in memory and never be written to disk

2022-02-10 09:01 UTC, KieranFrance approved these changes

2022-02-11 11:27 UTC, leonatherton requested changes
Can you rename IStorage to Storage please

`storageProvider` and `cls` look like they can probably be final too

The new import in BaseServlet looks like it is unused

Looks good otherwise

2022-02-18 11:30 UTC, daniel-warren requested changes

2022-02-18 11:44 UTC, KieranFrance requested changes

2022-02-18 11:44 UTC, KieranFrance commented on pom.xml
>      </dependencies>
As the remote storage is now in a new project do we still need this?

2022-03-02 15:12 UTC, leonatherton requested changes

2022-03-02 15:12 UTC, leonatherton commented on src/main/java/com/idrsolutions/microservice/storage/BaseStorage.java
> + * An abstract implementation of IStorage that pre-implements the File version of {@link #put(File, String, String)} to load the file into memory and put it through {@link #put(byte[], String, String
```suggestion
 * An abstract implementation of Storage that pre-implements the File version of {@link #put(File, String, String)} to load the file into memory and put it through {@link #put(byte[], String, String)}
```

2022-03-02 15:13 UTC, leonatherton approved these changes

2022-03-22 11:30 UTC, merged