Added database support
idrsolutions/base-microservice-example pull request #50
Opened 2022-02-10 10:01 UTC by JacobIDR

A continuation of [https://github.com/idrsolutions/base-microservice-example/pull/36](https://github.com/idrsolutions/base-microservice-example/pull/36)
This removes the IMap in favour of an abstraction that allows a database or an in memory map to be used to keep track of jobs.
Database support has been implemented to use a DataSource fetched from the Web Server, allowing clients fine control without needing to add lots of config options to our microservice. 
This DataSource technique also opens us up to connection pools, which enable connections to be cached and reused instead of being created for each transaction, which can be costly for performance.

2022-02-17 15:06 UTC, daniel-warren requested changes
Suggested various code style changes (some may also be applicable to the product microservices too) and added finality in some situations.

2022-02-17 15:06 UTC, daniel-warren commented on src/main/java/com/idrsolutions/microservice/BaseServlet.java
> +    private File outputFile(String filename, final String uuid, byte[] fileBytes) throws IOException {
```suggestion
    private File outputFile(final String filename, final String uuid, final byte[] fileBytes) throws IOException {
```

2022-02-17 15:06 UTC, daniel-warren commented on src/main/java/com/idrsolutions/microservice/BaseServlet.java
>      protected void doGet(HttpServletRequest request, HttpServletResponse response) {
```suggestion
    protected void doGet(final HttpServletRequest request, final HttpServletResponse response) {
```

2022-02-18 11:50 UTC, KieranFrance requested changes

2022-02-21 15:41 UTC, daniel-warren approved these changes

2022-02-24 15:25 UTC, leonatherton approved these changes

2022-03-22 11:27 UTC, merged