Feature/improve rmi and shutdown implementation
idrsolutions/base-microservice-example pull request #72
Opened 2023-11-02 16:27 UTC by leonatherton

As discussed:
- Resolve RMI shutdown issue
- Resolve Tomcat cleanup race
- Init/destroy RMI in base-microservice
- Init FileDeletionService after database
- Move registry from properties file to context attribute
- Single shared ProgressTracker instance
- Tidy ProcessUtils
- Changed RMI keys from `org.jpedal` to `com.idrsolutions` (& `id` to `uuid`)

If you have started implementing RMI on a child microservice then this will allow you to tidy things up like so:
https://github.com/idrsolutions/buildvu-microservice-example/commit/16ea2b5214a41c67e29dfdab2b1eb729c3d9036b

2023-11-02 17:00 UTC, daniel-warren requested changes

2023-11-02 17:00 UTC, daniel-warren commented on src/main/java/com/idrsolutions/microservice/utils/ProgressTracker.java
> +    }
Should the parameters be final?
```suggestion
    public ProgressTracker(final int port) throws RemoteException {
        super(port);
    }

    @Override
    public void finishedPageDecoding(final String uuid, final int rawPage) {
        DBHandler.getInstance().setCustomValue(uuid, "pagesConverted", String.valueOf(rawPage));
    }
```

2023-11-02 17:03 UTC, daniel-warren approved these changes

2023-11-08 15:06 UTC, Amy1612 approved these changes

2023-11-08 16:34 UTC, KieranFrance approved these changes

2023-11-22 15:46 UTC, merged